preset: recommended

risky: true

linting: true

enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow
  - align_double_arrow
  - blank_line_after_namespace
  - blank_line_after_opening_tag

disabled:
  - short_array_syntax
