language: php
php:
  - 7.0

services:
  - mysql

before_script:
  - mysql -e create database doesangue_test;
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - composer --version
#  - pip install --user codecov

script:
  - composer dumpautoload
  - vendor/bin/phpunit --coverage-clover=coverage.xml
#  - codecov

notifications:
  slack: mentedigital:duwI9LzVAI2ZgDbtie5vwpR7

env:
 - LARAVEL="5.3"

install: composer install

addons:
    code_climate:
        repo_token: 0cf44912ed4344a020d170ff41b89b3cadda2102e3c04f4e1316ce0d346e1268

after_success:
  - bash <(curl -s https://codecov.io/bash)
